
# Github action for releasing the binaries
name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        run: | 
          npm install
          npm run build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          files: |
            ./dist/component.css
            ./dist/component.js
            ./dist/outscale.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
